package com.example.forcars.ui.common.utils

class Marcas {

    companion object {
        val marca = listOf(
            "Todas las marcas",
            "Audi",
            "BMW",
            "Mercedes",
            "Seat",
            "Volkswagen",
            "Fiat",
            "Volvo",
            "Toyota",
            "Ford",
            "Citroen",
            "Renault",
            "Chevrolet",
            "Hyundai",
            "Kia",
            "Mazda",
            "Nissan",
            "Opel",
            "Peugeot",
            "Skoda",
            "Suzuki",
            "Tesla",
            "Dacia",
            "Honda",
            "Lexus",
            "Mitsubishi",
            "Alfa Romeo",
            "Dodge",
            "Jeep",
            "Land Rover",
            "Mini",
            "Porsche",
            "Smart",
            "Subaru",
            "SsangYong",
            "Abarth",
            "DS",
            "Infiniti",
            "Jaguar",
            "Lancia",
            "Lada",
            "Maserati",
            "MG",
            "Santana",
            "Saab",
            "Alpine",
            "Austin",
            "Bentley",
            "Chrysler",
            "Daewoo",
            "Ferrari",
            "Hummer",
            "Isuzu",
            "Lamborghini",
            "Lotus",
            "Mahindra",
            "Morgan",
            "Rover",
            "Rolls-Royce",
            "Tata",
            "Triumph",
            "Aston Martin",
            "Austin-Healey",
            "Bugatti",
            "Cadillac",
            "Caterham",
            "Daihatsu",
        )
    }
}